### ISSUE TITLE
修改甘特图数据报错的严重问题

### ISSUE THREAD

**Issue by mfkwgizhoujian** [jeremyjone/jz-gantt#11]
版本：v1.1.10
vue3使用组合式API方式对甘特图绑定的数据进行修改，除了置空外，所有其它操作全部报错，莫非是我写代码的姿势不对？错误截图如下：
![image](https://user-images.githubusercontent.com/33543763/147066322-16ee3ef6-3796-41bd-ac81-84c139bb2551.png)

测试代码截图如下：
![image](https://user-images.githubusercontent.com/33543763/147066481-713b3116-5fc7-4996-b017-fd11d9ac11ca.png)

**Comment by jeremyjone** [comment]
Hi: @mfkwgizhoujian 

这个问题确实是你传值姿势不对~😄

请确保 `index`、`startDate`、`endDate`、`children` 这四个属性的存在，前三个支持修改，最后一个是默认值。

参考 [文档](https://jeremyjone.github.io/jz-gantt/docs/root.html#data)

**Comment by mfkwgizhoujian** [comment]
> Hi: @mfkwgizhoujian
> 
> 这个问题确实是你传值姿势不对~😄
> 
> 请确保 `index`、`startDate`、`endDate`、`children` 这四个属性的存在，前三个支持修改，最后一个是默认值。
> 
> 参考 [文档](https://jeremyjone.github.io/jz-gantt/docs/root.html#data)

我刚试了，加上children: []，我把代码改成
dataList.value = [{
        id: '05',
        startTime: '2021-12-01',
        endTime: '2021-12-06',
        children: []
      }]，会变成空数据，必须使用index、startDate、endDate才正常，可是我既然已经设置了data-index、start-key和end-key，修改数据时为啥还必须使用默认的index、startDate、endDate呢，这样用起来很奇怪啊，另外children如果不传，默认是空数组会更方便点吧？

**Comment by mfkwgizhoujian** [comment]
@jeremyjone

**Comment by jeremyjone** [comment]
@mfkwgizhoujian 

已修复。
