### ISSUE TITLE
行高设置的问题

### ISSUE THREAD

**Issue by vinceliang1** [jeremyjone/jz-gantt#13]
如果动态设置改变了j-gantt组件的row-height属性，无法使得组件改变的行高

**Comment by jeremyjone** [comment]
@vinceliang1 请重现错误

**Comment by vinceliang1** [comment]
我在j-gantt组件的row-height属性设置了一个computed，它是根据size变量的值来取得对应的高度
![image](https://user-images.githubusercontent.com/52043463/147314336-ad6303c6-6ed4-4e77-ab28-7c9468e83ee3.png)
![image](https://user-images.githubusercontent.com/52043463/147314431-44fafad6-3e27-4313-8336-11042a2db634.png)
结果是这样现在：
![image](https://user-images.githubusercontent.com/52043463/147314564-c77bb14d-9312-4a31-b8ea-4a26a3f40037.png)
然后我点击修改rowHeight之后：
![image](https://user-images.githubusercontent.com/52043463/147314603-982a0423-6129-4a33-860c-7e03b5827c69.png)
![image](https://user-images.githubusercontent.com/52043463/147314625-f954a0d6-1c86-48e3-9f48-0ba213169214.png)
结果是这样现在：
![image](https://user-images.githubusercontent.com/52043463/147314666-8a67a5ca-0c46-4434-a11c-9f1b0306ad78.png)
rowHeight属性已经改变了，但是对应的gantt组件不重新响应渲染对应的行高

**Comment by jeremyjone** [comment]
@vinceliang1 

`row-height` 与 `col-size` 给完初始值，组件内会保存记录，不会修改了~后续仅随内部数据修改。

因为组件内部提供了修改的途径，如果可变，每次更新组件都会恢复到初始值。

如果你需要多种样式，可以通过 `v-if` 创建多个或者我看看最近更新一下~

**Comment by vinceliang1** [comment]
我尝试过使用v-if或者给组件添加key来让组件整个重新渲染，但是如果滚动了滚动条之后，整个组件重新渲染会页面样式错乱，
给组件添加key：
![image](https://user-images.githubusercontent.com/52043463/147326448-8bece7ab-6230-4b6d-a2b8-62fdf41f6688.png)
切换行高的时候改变组件的key让组件重新渲染
![image](https://user-images.githubusercontent.com/52043463/147326529-7286cd34-77ff-4f07-825a-ca32d15bf39b.png)
如果我不滚动滚动条进行切换页面是没有问题的：
![image](https://user-images.githubusercontent.com/52043463/147326656-4fae66d8-e191-419e-ad36-fa6dd4fc319e.png)
![image](https://user-images.githubusercontent.com/52043463/147326679-e5938db9-0342-49da-8464-61c5e4abcf9d.png)
如果我在页面切换的时候改变了滚动条的位置就会出现位置错乱，但是我再次滚动滚动条就恢复了：
切换前：
![image](https://user-images.githubusercontent.com/52043463/147326772-6aa3aca6-6169-4ac9-b0c2-5acaf7bfa980.png)
切换后：
![image](https://user-images.githubusercontent.com/52043463/147326810-120561d5-3864-436a-85d3-012d225b424b.png)
这时再次滚动滚动条才能正常：
![image](https://user-images.githubusercontent.com/52043463/147326834-1659988b-8d64-453c-a4b6-cc529d6f4676.png)
我是利用key来让整个组件重新渲染在这里，但是我之前也利用了v-if也是相同的效果，我想请问您有什么办法解决这个问题不，麻烦了

**Comment by jeremyjone** [comment]
我知道了，我看看怎么修改一下~

**Comment by jeremyjone** [comment]
@vinceliang1 升级到 `v.1.2.0` 试一下

**Comment by vinceliang1** [comment]
完美，解决了，非常感谢大佬呀~~~
