### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by vinceliang1** [jeremyjone/jz-gantt#17]
您好，请问能支持同一行多个甘特条的功能不？

**Comment by jeremyjone** [comment]
@vinceliang1 目前没有计划。而且我个人认为这样的需求背离了甘特的初衷

**Comment by vinceliang1** [comment]
@jeremyjone 好的，谢谢，主要是接到需求需要一行显示多个类型的任务进度，因此想问问可不可以支持，那我自己想想有什么办法实现

**Comment by jeremyjone** [comment]
@vinceliang1 不知道问你具体是什么需求。但是大多数情况下，都可以将任务进行拆分，按层级排列，每个具体的任务都可以放在一个层级下，这也是分层的意义。

PS：我在做连线功能，这可能也会帮助到你这种需求
