### ISSUE TITLE
[BUG]更新到1.3.0版本样式错乱了

### ISSUE THREAD

**Issue by vinceliang1** [jeremyjone/jz-gantt#18]
您好，更新到1.3.0版本样式会错乱，原本的1.2.0版本的效果：
![image](https://user-images.githubusercontent.com/52043463/150671521-23f0ea81-81db-4519-96c1-9bf2ee89ae1c.png)
更新到1.3.0版本之后的效果是这样的：
![image](https://user-images.githubusercontent.com/52043463/150671613-baeae1e1-198c-4c09-989c-7f34f3ee30a1.png)
其他的代码都不变，是不是更新到1.3.0之后需要做什么其他的设置？

**Comment by jeremyjone** [comment]
目前没有发现问题。我明天再看一下。

你看一下你的样式是否有问题？可否附上相关代码？

**Comment by vinceliang1** [comment]
您好，这是我的相关代码，这是html：
![image](https://user-images.githubusercontent.com/52043463/150709702-e8f5aeb8-e0e1-42c0-a7c2-34671014cb50.png)
这是css：
![image](https://user-images.githubusercontent.com/52043463/150709817-e07be396-0c6c-4727-961c-6cba1423d8ac.png)

**Comment by jeremyjone** [comment]
@vinceliang1  我按照你的代码试了一下，没有发现问题。

```html
<a-modal v-model:visible="visible" width="100%" wrap-class-name="full-modal">
  <template #title>
    <a-button>添加款式</a-button>
  </template>

  <div style="width: 100%; height: 100%; overflow: auto">
    <j-gantt data-index="index" :data="dataList" :show-setting-btn="false">
      <j-gantt-column label="index" />
    </j-gantt>
  </div>
</a-modal>
```

一般来说，这可能是样式被覆盖的问题。

1、请检查 `gt-root` 的 `flex-direction` 属性是否被置为 `column`
2、请检查 `gt-root` 的 `display` 属性是否为 `flex`
3、上述属性没有问题的话，请检查其他属性是否有被覆盖的情况

如果都没有问题，请复现问题代码（不是贴图），并把复现步骤描述清楚，谢谢。

**Comment by vinceliang1** [comment]
好的，我再试试市哪里被样式覆盖了，感谢
