### ISSUE TITLE
[BUG] new data 还未请求回来时 newData length 不存在 导致页面没刷新

### ISSUE THREAD

**Issue by dazhaocode** [jeremyjone/jz-gantt#19]
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/45939769/158131043-11f12fca-99d0-499d-abe7-94ab6b1f80bc.png">

<img width="683" alt="image" src="https://user-images.githubusercontent.com/45939769/158130910-4548bfec-9574-41b6-b3ef-220dd5b5edbe.png">

**Comment by jeremyjone** [comment]
@dazhaocode 数据还未请求回来的时候，为什么会用到这里？这里只有数据更新时才会调用。可否给一个用例？

**Comment by dazhaocode** [comment]
@jeremyjone 
 sure! open this url :https://codesandbox.io/s/serene-poitras-3r8w8h
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45939769/158301005-06c33873-7859-471d-9b31-74431b9083ef.png">
code is here: https://github.com/dazhaocode/jzgantt-case.git

**Comment by jeremyjone** [comment]
@dazhaocode 我看到了。

问题：您的数据中没有 `children` 键名。

解决方案：请确保数据中 `children` 、`index`、`startDate` 以及 `endDate` 四个属性的存在（其中后三项可以通过传值修改键名）。为了确保所有数据的统一，在定义数据类型的同时，您就应该定义它：

```ts
interface IData {
  id: number;
  name: string;
  startDate: string;
  endDate: string;
  children: Array<IData>;
}
```

当数据类型正确的时候，所有数据都会正确显示。


===

简要说明：为了保证数据的统一，以及每一层数据的准确性，我们需要确保数据中至少4个属性的存在：

- `index` 确保数据的唯一性，它应对于所有数据全局唯一的。通过 [data-index](https://jeremyjone.github.io/jz-gantt/docs/root.html#data-index) 替换
- `children` 可以使数据层级嵌套，如果没有子集，只需要置空即可
- `startDate` 可以在甘特图中正确渲染数据的起始日期。通过 [start-key](https://jeremyjone.github.io/jz-gantt/docs/root.html#start-key) 替换
- `endDate` 可以在甘特图中正确渲染数据的截止日期。通过 [end-key](https://jeremyjone.github.io/jz-gantt/docs/root.html#end-key) 替换

详细内容，请见 [文档 - data](https://jeremyjone.github.io/jz-gantt/docs/root.html#data)
