### ISSUE TITLE
甘特图中一项内容能展示两个不同时间段的数据吗。0.17版本start-key和end-key好像不生效

### ISSUE THREAD

**Issue by FizzlingFish** [jeremyjone/jz-gantt#25]

**Comment by jeremyjone** [comment]
第一个问题，参看 #4 

第二个问题，请复现问题

**Comment by FizzlingFish** [comment]
感谢大大回复第一个问题用slot:content解决了一半，一项内容有了两条甘特图线段，有方法能让两条线段的起始截止时间不同吗。有个

**Comment by jeremyjone** [comment]
@FizzlingFish 逻辑上不可以。原因还是参见 #4 。

但如果你需要，我觉得你可以分别在两行进行处理，至于 bottom 的样式线，可以重载样式处理一下，这样看起来就像在一行了

我没试过，只是觉得应该行哈~
