### ISSUE TITLE
您好，甘特图每次只想展示一个月的数据，可以按月份切割甘特图吗？

### ISSUE THREAD

**Issue by DDQH** [jeremyjone/jz-gantt#26]
甘特图按月份切换数据，但是好像会自动计算那个小块块，好像是根据页面宽度在变化？想问一下这个可以怎么改一下，麻烦大佬了

**Comment by jeremyjone** [comment]
@DDQH 不支持右侧按月切割

**Comment by DDQH** [comment]
大佬您好，感谢回复。我可能没说明白，看文档说根据日期自动计算的，比如整个数据的结束时间到2022-05-13，列宽选择中的话，右侧那边还是会到6月8号去，而我只想显示五月的，这个是不支持更改的是吗？

**Comment by DDQH** [comment]
> @DDQH 我知道你说的这点，在写这个的时候考虑过。
> 
> 先说原因吧。因为日期的宽度是已知的，所以每天、每月其实都是固定宽度，如果显示的宽度过大，则会导致右侧有留白，不好看，所以，在内部的逻辑上，其实结束日期是取`endDate`和`最贴合屏幕的右侧日期`的最大值这样就不会有留白了。
> 
> 所以，这是根据浏览器决定的。如果你把浏览器宽度缩小，会达到你的效果
> 
> 以上



> @DDQH 我知道你说的这点，在写这个的时候考虑过。
> 
> 先说原因吧。因为日期的宽度是已知的，所以每天、每月其实都是固定宽度，如果显示的宽度过大，则会导致右侧有留白，不好看，所以，在内部的逻辑上，其实结束日期是取`endDate`和`最贴合屏幕的右侧日期`的最大值这样就不会有留白了。
> 
> 所以，这是根据浏览器决定的。如果你把浏览器宽度缩小，会达到你的效果
> 
> 以上

好的，了解了。谢谢大佬解惑~

**Comment by DDQH** [comment]
> 

好的，了解了。插件很实用，感谢大佬~
