### ISSUE TITLE
如何一行中显示多个任务

### ISSUE THREAD

**Issue by Messilimeng** [jeremyjone/jz-gantt#4]
你好看了你的组件 写的很好 ，但是我有个问题想咨询一下，因为我们的需求是一个小组 不能同时做两个任务，所以每个任务都是接在前一个任务后的,所以您这个组件可以一行放多个任务条吗？

**Comment by jeremyjone** [comment]
@Messilimeng 首先我要明确的是，甘特图的要义应该是一行一个任务。

你所说的内容，应该可以通过多行解决。如果执意一行多任务的需求，我觉得可以通过 `j-gantt-slider` 的自定义 slot 重新定义显示样式来解决。

**Comment by Messilimeng** [comment]
@jeremyjone 好的 感谢 我看看如何结合需求来处理

**Comment by Delicatesparks** [comment]
> @Messilimeng 首先我要明确的是，甘特图的要义应该是一行一个任务。
> 
> 你所说的内容，应该可以通过多行解决。如果执意一行多任务的需求，我觉得可以通过 `j-gantt-slider` 的自定义 slot 重新定义显示样式来解决。
> 
> 最后，我认为你的需求，应该可以通过数据控制来解决。当前版本的 `JzGantt` 没有前置后置任务功能，所以通过数据控制时间，和重载甘特条，将后置任务置灰等方式来解决。

请问怎么定义slot才可以一行内多个任务呢
