### ISSUE TITLE
JGanttColumn重复加载的问题

### ISSUE THREAD

**Issue by zhuzhuzhuTA** [jeremyjone/jz-gantt#5]
打开带有甘特图的页面后跳转到别的页面再跳转回来时,表格内容会重复加载.
若项目中只有一处页面使用甘特图,可以通过keep-alive避免,但是有多出页面使用甘特图,依然会出现这种情况.

**Comment by zhuzhuzhuTA** [comment]
> 打开带有甘特图的页面后跳转到别的页面再跳转回来时,表格内容会重复加载.

当前版本1.1.2

**Comment by jeremyjone** [comment]
@zhuzhuzhuTA 收到您的反馈。我在测试中遇到过，但是实际应用中我一直使用Keep-alive，所以没有在意。我会尽快查看问题所在，请留意后续更新。:)

**Comment by jeremyjone** [comment]
@zhuzhuzhuTA 问题已修复。请更新至 `v1.1.4` 后试一下
