### ISSUE TITLE
动态渲染column

### ISSUE THREAD

**Issue by standardsmile** [jeremyjone/jz-gantt#9]
您好 这个j-gantt-column支持动态渲染吗 我想显示的列是根据不同需求通过配置出来的需要显示哪几个字段 能否支持v-for循环

**Comment by jeremyjone** [comment]
与所有普通 html 标签的用法一样。你可以使用循环，前提是确保至少它的属性（label）正确即可。

**Comment by standardsmile** [comment]
> 
我尝试了两种写法：
<div v-for="key in keys">
        <j-gantt-column :label="key" width="150">
        </j-gantt-column>
</div>

 <j-gantt-column v-for="key in keys" :label="key" width="150"></j-gantt-column>

我是在demo上这样写的 keys定义的是["name","index"]，name和index是data里的键名 但是没渲染出来列

**Comment by standardsmile** [comment]
> 
我尝试了两种写法：
<div v-for="key in keys">
        <j-gantt-column :label="key" width="150">
        </j-gantt-column>
</div>

 <j-gantt-column v-for="key in keys" :label="key" width="150"></j-gantt-column>

我是在demo上这样写的 keys定义的是["name","index"]，name和index是data里的键名 但是没渲染出来列

**Comment by standardsmile** [comment]
我尝试了两种写法：
`<div v-for="key in keys">
        <j-gantt-column :label="key" width="150">
        </j-gantt-column>
</div>`

` <j-gantt-column v-for="key in keys" :label="key" width="150"></j-gantt-column>`

我是在demo上这样写的 keys定义的是["name","index"]，name和index是data里的键名 但是没渲染出来列

**Comment by standardsmile** [comment]
> 与所有普通 html 标签的用法一样。你可以使用循环，前提是确保至少它的属性（label）正确即可。

`<div v-for="key in keys">
        <j-gantt-column :label="key" width="150">
        </j-gantt-column>
</div>`

`<j-gantt-column v-for="key in keys" :label="key" width="150"></j-gantt-column>`

**Comment by jeremyjone** [comment]
理解您的意思了。我试了一下，确实不能渲染。目前系统内部将所有插槽进行了拦截二次处理，所以对于循环，没有进行显示反馈。

虽然您这种写法看上去更省时省力，但我仍然不建议这么做，因为每一列都应当具有特定的效果，后续可以带来更加方便的自定义方式。如果您需要一个可变的列，可以通过 `v-if` 进行切换即可。

**Comment by standardsmile** [comment]
好的 谢谢～
